add_subdirectory(external/raylib)

target_compile_definitions(raylib PRIVATE EXTERNAL_CONFIG_FLAGS)
target_compile_definitions(raylib PRIVATE SUPPORT_MODULE_RSHAPES)
target_compile_definitions(raylib PRIVATE SUPPORT_MODULE_RTEXTURES)
target_compile_definitions(raylib PRIVATE SUPPORT_MODULE_RTEXT)
target_compile_definitions(raylib PRIVATE SUPPORT_MODULE_RMODELS)
target_compile_definitions(raylib PRIVATE SUPPORT_MODULE_RAUDIO)
target_compile_definitions(raylib PRIVATE SUPPORT_CAMERA_SYSTEM)
target_compile_definitions(raylib PRIVATE SUPPORT_GESTURES_SYSTEM)
target_compile_definitions(raylib PRIVATE SUPPORT_RPRAND_GENERATOR)
target_compile_definitions(raylib PRIVATE SUPPORT_MOUSE_GESTURES)
target_compile_definitions(raylib PRIVATE SUPPORT_SSH_KEYBOARD_RPI)
target_compile_definitions(raylib PRIVATE SUPPORT_WINMM_HIGHRES_TIMER)
#target_compile_definitions(raylib PRIVATE SUPPORT_BUSY_WAIT_LOOP)
target_compile_definitions(raylib PRIVATE SUPPORT_PARTIALBUSY_WAIT_LOOP)
target_compile_definitions(raylib PRIVATE SUPPORT_SCREEN_CAPTURE)
target_compile_definitions(raylib PRIVATE SUPPORT_GIF_RECORDING)
target_compile_definitions(raylib PRIVATE SUPPORT_COMPRESSION_API)
target_compile_definitions(raylib PRIVATE SUPPORT_AUTOMATION_EVENTS)
#target_compile_definitions(raylib PRIVATE SUPPORT_CUSTOM_FRAME_CONTROL)
# target_compile_definitions(raylib PRIVATE "MAX_FILEPATH_CAPACITY=8192")
# target_compile_definitions(raylib PRIVATE "MAX_FILEPATH_LENGTH=4096")
# target_compile_definitions(raylib PRIVATE "MAX_KEYBOARD_KEYS=512")
# target_compile_definitions(raylib PRIVATE "MAX_MOUSE_BUTTONS=8")
# target_compile_definitions(raylib PRIVATE "MAX_GAMEPADS=4")
# target_compile_definitions(raylib PRIVATE "MAX_GAMEPAD_AXIS=8")
# target_compile_definitions(raylib PRIVATE "MAX_GAMEPAD_AXIS=8")
# target_compile_definitions(raylib PRIVATE "MAX_GAMEPAD_BUTTONS=32")
# target_compile_definitions(raylib PRIVATE "MAX_TOUCH_POINTS=8")
# target_compile_definitions(raylib PRIVATE "MAX_KEY_PRESSED_QUEUE=16")
# target_compile_definitions(raylib PRIVATE "MAX_CHAR_PRESSED_QUEUE=16")
# target_compile_definitions(raylib PRIVATE "MAX_DECOMPRESSION_SIZE=64")
# target_compile_definitions(raylib PRIVATE "MAX_AUTOMATION_EVENTS=16384")
# #target_compile_definitions(raylib PRIVATE RLGL_ENABLE_OPENGL_DEBUG_CONTEXT)
# #target_compile_definitions(raylib PRIVATE RLGL_SHOW_GL_DETAILS_INFO)
# #target_compile_definitions(raylib PRIVATE "RL_DEFAULT_BATCH_BUFFER_ELEMENTS=4096")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_BATCH_BUFFERS=1")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_BATCH_DRAWCALLS=256")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_BATCH_MAX_TEXTURE_UNITS=4")
# target_compile_definitions(raylib PRIVATE "RL_MAX_MATRIX_STACK_SIZE=32")
# target_compile_definitions(raylib PRIVATE "RL_MAX_SHADER_LOCATIONS=32")
target_compile_definitions(raylib PRIVATE "RL_CULL_DISTANCE_NEAR=0.01")
target_compile_definitions(raylib PRIVATE "RL_CULL_DISTANCE_FAR=10000.0")

# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_ATTRIB_NAME_POSITION=\"vertexPosition\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD=\"vertexTexCoord\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_ATTRIB_NAME_NORMAL=\"vertexNormal\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_ATTRIB_NAME_COLOR=\"vertexColor\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_ATTRIB_NAME_TANGENT=\"vertexTangent\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_ATTRIB_NAME_TEXCOORD2=\"vertexTexCoord2\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_UNIFORM_NAME_MVP=\"mvp\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_UNIFORM_NAME_VIEW=\"matView\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_UNIFORM_NAME_PROJECTION=\"matProjection\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_UNIFORM_NAME_MODEL=\"matModel\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_UNIFORM_NAME_NORMAL=\"matNormal\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_UNIFORM_NAME_COLOR=\"colDiffuse\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE0=\"texture0\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE1=\"texture1\"")
# target_compile_definitions(raylib PRIVATE "RL_DEFAULT_SHADER_SAMPLER2D_NAME_TEXTURE2=\"texture2\"")

# target_compile_definitions(raylib PRIVATE SUPPORT_QUADS_DRAW_MODE)
# target_compile_definitions(raylib PRIVATE "SPLINE_SEGMENT_DIVISIONS=24")


target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_PNG)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_BMP)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_TGA)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_JPG)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_GIF)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_QOI)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_PSD)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_DDS)
#target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_HDR)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_PIC)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_KTX)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_ASTC)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_PKM)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_PVR)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_SVG)
target_compile_definitions(raylib PRIVATE SUPPORT_IMAGE_EXPORT)
target_compile_definitions(raylib PRIVATE SUPPORT_IMAGE_GENERATION)
target_compile_definitions(raylib PRIVATE SUPPORT_IMAGE_MANIPULATION)


target_compile_definitions(raylib PRIVATE SUPPORT_DEFAULT_FONT)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_FNT)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_TTF)
target_compile_definitions(raylib PRIVATE SUPPORT_TEXT_MANIPULATION)
target_compile_definitions(raylib PRIVATE SUPPORT_FONT_ATLAS_WHITE_REC)

# target_compile_definitions(raylib PRIVATE "MAX_TEXT_BUFFER_LENGTH=1024")
# target_compile_definitions(raylib PRIVATE "MAX_TEXTSPLIT_COUNT=128")

target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_OBJ)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_MTL)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_IQM)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_GLTF)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_VOX)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_M3D)
target_compile_definitions(raylib PRIVATE SUPPORT_MESH_GENERATION)

# target_compile_definitions(raylib PRIVATE "MAX_MATERIAL_MAPS=12")
# target_compile_definitions(raylib PRIVATE "MAX_MESH_VERTEX_BUFFERS=7")

target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_WAV)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_OGG)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_MP3)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_QOA)
# #target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_FLAC)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_XM)
target_compile_definitions(raylib PRIVATE SUPPORT_FILEFORMAT_MOD)

# target_compile_definitions(raylib PRIVATE "AUDIO_DEVICE_FORMAT=ma_format_f32")
# target_compile_definitions(raylib PRIVATE "AUDIO_DEVICE_CHANNELS=2")
# target_compile_definitions(raylib PRIVATE "AUDIO_DEVICE_SAMPLE_RATE=0")

# target_compile_definitions(raylib PRIVATE "MAX_AUDIO_BUFFER_POOL_CHANNELS=16")

target_compile_definitions(raylib PRIVATE SUPPORT_STANDARD_FILEIO)
target_compile_definitions(raylib PRIVATE SUPPORT_TRACELOG)

# target_compile_definitions(raylib PRIVATE "MAX_TRACELOG_MSG_LENGTH=256")
